INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,1,'EASY');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,2,'MEDIUM');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,3,'HARD');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,4,'EVIL');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,6,'INSANE');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,2,'MEDIUM 2');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,7,'USA_TODAY_12_15_08');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,5,'FIENDISH');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,4,'USA_TODAY_01_08_09');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,3,'USA_TODAY_12_23_08');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,5,'USA_TODAY_12_19_08');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,4,'USA_TODAY_12_24_08');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,3,'USA_TODAY_12_29_08');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,3,'CHARLOTTE_OBSERVER_01_02_09');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,4,'USA_TODAY_12_31_08');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,3,'USA_TODAY_12_16_08');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,4,'CHARLOTTE_OBSERVER_01_01_09');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,5,'USA_TODAY_01_02_09');

INSERT INTO BOARD (BOARD_HEIGHT,BOARD_WIDTH,BOARD_DIFFICULTY_LEVEL,BOARD_DIFFICULTY_TEXT)
VALUES (9,9,3,'USA_TODAY_12_22_08');