DROP TABLE BOARD_DETAIL;

CREATE TABLE BOARD_DETAIL (
	BOARD_ID INTEGER,
	BOARD_FULLARRAY VARCHAR(256),
	BOARD_QUADRANT_1 VARCHAR(128),
	BOARD_QUADRANT_2 VARCHAR(128),
	BOARD_QUADRANT_3 VARCHAR(128),
	BOARD_QUADRANT_4 VARCHAR(128),
	BOARD_QUADRANT_5 VARCHAR(128),
	BOARD_QUADRANT_6 VARCHAR(128),
	BOARD_QUADRANT_7 VARCHAR(128),
	BOARD_QUADRANT_8 VARCHAR(128),
	BOARD_QUADRANT_9 VARCHAR(128),
	PRIMARY KEY (BOARD_ID),
	CONSTRAINT FK_BOARD_ID
	FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID)
);
